version: "3.8"
services:
  #   mongodb:
  #     image: mongo
  #     ports:
  #       - '27017:27017'
  #     volumes:
  #       - mongodb_data:/data/db
  #     environment:
  #       MONGO_INITDB_ROOT_USERNAME: root
  #       MONGO_INITDB_ROOT_PASSWORD: password

  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "9229:9229"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    command: php artisan serve
